import { DishDto } from '@atocha/menu-matriarch/shared/data-access-dtos';
import { SeedDataIds } from './seed-data-ids';

export function createDishData(
  uid: string,
  ids: SeedDataIds
): Partial<DishDto>[] {
  return [
    {
      id: ids.dishIds.cornbread,
      uid,
      name: 'Cornbread',
      description: 'Made in the skillet with brown butter',
      type: 'side',
      link: 'https://cooking.nytimes.com/recipes/1016965-brown-butter-skillet-cornbread',
      menuIds: [ids.menuIds.menu],
      mealIds: [ids.mealIds.southernClassic],
      tagIds: [ids.tagIds.vegetarian],
      usages: 1,
    },
    {
      id: ids.dishIds.enchiladas,
      uid,
      name: 'Enchiladas',
      link: 'https://cooking.nytimes.com/recipes/1018152-enchiladas-con-carne',
      menuIds: [ids.menuIds.menu],
      usages: 1,
    },
    {
      id: ids.dishIds.friedChicken,
      uid,
      name: 'Fried Chicken',
      link: 'https://cooking.nytimes.com/recipes/1018219-buttermilk-fried-chicken',
      menuIds: [ids.menuIds.menu],
      mealIds: [ids.mealIds.southernClassic],
      usages: 1,
    },
    {
      id: ids.dishIds.greekSalad,
      uid,
      name: 'Greek Salad',
      tagIds: [ids.tagIds.vegetarian],
    },
    {
      id: ids.dishIds.huevosRotos,
      uid,
      name: 'Huevos Rotos',
      link: 'https://cooking.nytimes.com/recipes/1020055-huevos-rotos-broken-eggs',
      ingredientIds: [
        ids.ingredientIds.eggs,
        ids.ingredientIds.garlic,
        ids.ingredientIds.oliveOil,
        ids.ingredientIds.onion,
        ids.ingredientIds.paprika,
        ids.ingredientIds.pepper,
        ids.ingredientIds.potato,
        ids.ingredientIds.salt,
      ],
      tagIds: [ids.tagIds.vegetarian],
    },
    {
      id: ids.dishIds.macAndCheese,
      uid,
      name: 'Macaroni and Cheese',
      description: 'Delicious baked noodles from the USA',
      type: 'side',
      link: 'https://cooking.nytimes.com/recipes/1015825-creamy-macaroni-and-cheese',
      menuIds: [ids.menuIds.menu],
      mealIds: [ids.mealIds.southernClassic],
      tagIds: [ids.tagIds.vegetarian],
      usages: 1,
    },
    {
      id: ids.dishIds.misoSoup,
      uid,
      name: 'Miso Soup',
      type: 'side',
      menuIds: [ids.menuIds.menu],
      mealIds: [ids.mealIds.sushiDinner],
      tagIds: [ids.tagIds.vegan, ids.tagIds.vegetarian],
      usages: 1,
    },
    {
      id: ids.dishIds.pizza,
      uid,
      name: 'Pizza',
      description: 'Delicious round vessel from Italy',
      link: 'https://cooking.nytimes.com/guides/1-how-to-make-pizza',
      menuIds: [ids.menuIds.menu],
      tagIds: [ids.tagIds.vegetarian],
      usages: 1,
    },
    {
      id: ids.dishIds.redLentilSoup,
      uid,
      name: 'Red Lentil Soup',
      link: 'https://cooking.nytimes.com/recipes/1016062-red-lentil-soup-with-lemon',
      menuIds: [ids.menuIds.menu],
      tagIds: [ids.tagIds.vegan, ids.tagIds.vegetarian],
      usages: 1,
    },
    {
      id: ids.dishIds.roastedCauliflower,
      uid,
      name: 'Roasted Cauliflower',
      link: 'https://cooking.nytimes.com/recipes/7588-roasted-cauliflower',
      type: 'side',
      tagIds: [ids.tagIds.easy, ids.tagIds.vegan, ids.tagIds.vegetarian],
    },
    {
      id: ids.dishIds.salmonBurgers,
      uid,
      name: 'Salmon Burgers',
      link: 'https://cooking.nytimes.com/recipes/7131-salmon-burgers',
      menuIds: [ids.menuIds.menu],
      tagIds: [ids.tagIds.pescatarian],
      usages: 1,
    },
    {
      id: ids.dishIds.sushi,
      uid,
      name: 'Sushi',
      description: 'Delicious tiny vessels from Japan',
      menuIds: [ids.menuIds.menu],
      mealIds: [ids.mealIds.sushiDinner],
      tagIds: [ids.tagIds.pescatarian],
      usages: 1,
    },
    {
      id: ids.dishIds.sweetPotatoFries,
      uid,
      name: 'Sweet Potato Fries',
      type: 'side',
      menuIds: [ids.menuIds.menu],
      tagIds: [ids.tagIds.vegan, ids.tagIds.vegetarian],
      usages: 1,
    },
    {
      id: ids.dishIds.tiramisu,
      uid,
      name: 'Tiramisu',
      description: 'Delicious coffee-flavored Italian cake',
      link: 'https://cooking.nytimes.com/recipes/1018684-classic-tiramisu',
      type: 'dessert',
      menuIds: [ids.menuIds.menu],
      tagIds: [],
      usages: 2,
    },
    {
      id: ids.dishIds.thaiCurry,
      uid,
      name: 'Thai Curry',
      description: 'Delicious fragrant stew from Thailand',
      link: 'https://cooking.nytimes.com/recipes/1015694-vegan-thai-curry-vegetables',
      menuIds: [ids.menuIds.menu],
      tagIds: [ids.tagIds.easy, ids.tagIds.vegan, ids.tagIds.vegetarian],
      usages: 1,
    },
  ];
}
