# Settings in the [build] context are global and are applied to
# all contexts unless otherwise overridden by more specific contexts.

[build]
  base = "/"
  publish = "dist/globetrotter"
  command = "nx build globetrotter"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
